### ISSUE TITLE
Cannot download photos

### ISSUE THREAD

**Issue by aartek** [lukekarrys/instagram-download#15]
Application throws `instagram-download:api API error SyntaxError: Unexpected token < in JSON at position 0` 
`json` dir is empty.

```
C:\Users\Artur\Desktop>instagram-download --user=USER --token=TOKEN --dir="c:\users\artur\desktop\instaphotos"
  instagram-download:cli { _: [], refresh: false, full: false, read: false, doctor: false, get_token: false, user: 'USER', token: 'TOKEN', dir: 'c:\\users\\artur\\desktop\\instaphotos' } +0ms
  instagram-download:options OPT _  +30ms
  instagram-download:options OPT refresh false +3ms
  instagram-download:options OPT full false +1ms
  instagram-download:options OPT read false +2ms
  instagram-download:options OPT doctor false +1ms
  instagram-download:options OPT get_token false +1ms
  instagram-download:options OPT user USER+1ms
  instagram-download:options OPT token TOKEN +1ms
  instagram-download:options OPT dir c:\users\artur\desktop\instaphotos +0ms
  instagram-download:download User dir c:\users\artur\desktop\instaphotos\USER+6ms
  instagram-download:download Json dir c:\users\artur\desktop\instaphotos\USER\json +2ms
  instagram-download:download Media dir c:\users\artur\desktop\instaphotos\USER\media +1ms
  instagram-download:options OPT dir c:\users\artur\desktop\instaphotos +13ms
  instagram-download:options OPT user USER+0ms
  instagram-download:read Reading directory c:\users\artur\desktop\instaphotos\USER\json +0ms
  instagram-download:api API calls left undefined +375ms
  instagram-download:api API error SyntaxError: Unexpected token < in JSON at position 0 +2ms
```

Run on Windows 10 with command `instagram-download --user=USER --token=TOKEN --dir="c:\users\artur\desktop\instaphotos"`

node version: v6.2.1

Of course token and username are correct. 
Any idea how to fix it?

**Comment by lukekarrys** [comment]
I couldn't reproduce this with my own user and token. From a quick glance it looks like it's an error from the underlying `instagram-node` library being used as its trying to run `JSON.parse` on something that the API is returning that isn't JSON.

I just published `v2.2.5` which adds some more error logging, so if you update and try again hopefully it should now show what the actual error is.

**Comment by aartek** [comment]
Log from `v2.2.5` doesn't help much.

```
 instagram-download:api API error SyntaxError: Unexpected token < in JSON at position 0 +1ms
  instagram-download:api SyntaxError: Unexpected token < in JSON at position 0
    at Object.parse (native)
    at IncomingMessage.<anonymous> (C:\Users\Artur\AppData\Roaming\npm\node_modules\instagram-download\node_modules\instagram-node\lib\instagram.js:192:27)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9) +1ms
  instagram-download:api <!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en" class="no-js lt-ie9 lt-ie8 lt-ie7 not-logged-in "> <![endif]-->
<!--[if IE 7]>         <html lang="en" class="no-js lt-ie9 lt-ie8 not-logged-in "> <![endif]-->
<!--[if IE 8]>         <html lang="en" class="no-js lt-ie9 not-logged-in "> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en" class="no-js not-logged-in "> <!--<![endif]-->
    <head>

    <script type="text/javascript">window._timings = {"domLoading": Date.now()}</script>

        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
...
...
...
```

For me, it seems, a wrong request is made, so instagram returns a `html` instead of `json`. 

Here is the code of this html response: http://hastebin.com/keticakere.xml. It looks like `404` page.

**Comment by lukekarrys** [comment]
It's helpful to know that the response is a 404 page I think. I think this is returned from [`instagram-node`](https://www.npmjs.com/package/instagram-node) in this case. Can you try your access token with that library using the `user_media_recent` method? It should look something like this.

``` js
var ig = require('instagram-node').instagram();
ig.use({ access_token: 'YOUR_ACCESS_TOKEN' });

ig.user_media_recent('user_id', function(err, medias, pagination, remaining, limit) {
  // See what each argument is in here
});
```

**Comment by aartek** [comment]
The reason is trivial.  My `username` is not my `user_id`. I don't know if username is always different than `user_id`, but if not, it's probably because my account is related with facebook account.

By the way, it seems that `user_id` is first part of `access_token`, so you could omit the `--user` param. 
`access_token` has format `<user_id>.<something>.<token>`

**Comment by lukekarrys** [comment]
From what I've seen `username` has always been different than `user_id`. But the accounts I've used aren't attached to facebook accounts.

The access_token format used to be different, but that is good to know now :)

Hopefully everything is working for you now. Let me know if anything else isn't working.
